name: Unlock Next Step
on:
  pull_request:
    types: [closed]
jobs:
  unlock-next:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Unlock next step on fork
        run: |
          # Récupérer le dépôt du fork de l'étudiant
          git remote add student-fork https://github.com/${{ github.actor }}/repo-name.git
          git fetch student-fork

          # Si la PR est sur etape1, débloquer etape2 sur le fork de l'étudiant
          if [ "${{ github.event.pull_request.base.ref }}" == "etape1" ]; then
            git checkout etape2
            git push student-fork etape2
          # Si la PR est sur etape2, débloquer etape3 sur le fork de l'étudiant
          elif [ "${{ github.event.pull_request.base.ref }}" == "etape2" ]; then
            git checkout etape3
            git push student-fork etape3
          # Si la PR est sur etape3, débloquer etape4 sur le fork de l'étudiant
          elif [ "${{ github.event.pull_request.base.ref }}" == "etape3" ]; then
            git checkout etape4
            git push student-fork etape4
          # Si la PR est sur etape4, débloquer etape5 sur le fork de l'étudiant
          elif [ "${{ github.event.pull_request.base.ref }}" == "etape4" ]; then
            git checkout etape5
            git push student-fork etape5
          fi
