name: Valider l'étape SQL
on:
  pull_request:
    branches:
      - etape1
      - etape2
      - etape3
      - etape4
      - etape5

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Vérifier la structure SQL
        run: |
          if grep -q "CREATE TABLE Livres" etape1.sql; then
            echo "Table Livres trouvée ! ✅"
          else
            echo "❌ ERREUR : La table Livres n'a pas été créée."
            exit 1
          fi
